DROP TABLE IF EXISTS USER ;

CREATE TABLE  "USER" (
	
	"NAME" VARCHAR2(40) NOT NULL,
	"APELLIDOS" VARCHAR2(40),
	"EMAIL" VARCHAR2(100) NOT NULL PRIMARY KEY,
	"PASSWORD" VARCHAR2(100) NOT NULL,
	"NUM_TARJETA" NUMBER,
	"CVV" NUMBER,
	"CADUCIDAD" VARCHAR2(7)
);