DROP TABLE IF EXISTS MATRICULAS;

CREATE TABLE  "MATRICULAS" (
	"EMAIL" VARCHAR2(100) NOT NULL PRIMARY KEY,
	"MATRICULA1" VARCHAR2(6) NOT NULL,
	"MATRICULA2" VARCHAR2(6),
	"MATRICULA3" VARCHAR2(6),
	"MATRICULA4" VARCHAR2(6),
	"MATRICULA5" VARCHAR2(6)
);